# fly.toml app configuration file generated for socializer on 2023-10-24T15:57:53+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "socializer"
primary_region = "ams"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
